[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
gas_reports = ["OmamoriNFT", "OmamoriRender", "MaterialRegistryPalette"]
via_ir = true

# HyperEVM Network Configuration
rpc_url = "https://rpc.hyperliquid.xyz/evm"
chain_id = 999

# Test configuration
[profile.default.fuzz]
runs = 1000

# CI configuration
[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

# Local development
[profile.local]
rpc_url = "http://localhost:8545"
chain_id = 31337

# Remappings for cleaner imports
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@forge-std/=lib/forge-std/src/"
]

# RPC endpoints
[rpc_endpoints]
hyperliquid = "https://rpc.hyperliquid.xyz/evm"
local = "http://localhost:8545"

# Etherscan configuration for contract verification
[etherscan]
hyperliquid = { key = "${HYPERLIQUID_API_KEY}", url = "https://hyperevmscan.io/api" }