// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://impoplixuoggwnzgvqvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltcG9wbGl4dW9nZ3duemd2cXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzkwMTIsImV4cCI6MjA3MzgxNTAxMn0.fYiAYP0vp9OeHX06VIyrv7FkxLAmPNtY6ZGyHWbEMrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});